name: Publish
on:
  push:
    branches:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}"

      - name: install dependencies
        run: npm ci

      - name: increment version
        run: git config user.email "joaotextor@gmail.com" && git config user.name "João Textor" && npm version patch

      - name: run tests
        run: npm run lint && npm run test

      - name: build package
        run: npm run build

      - name: publish package
        run: npm publish -access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
